### ISSUE TITLE
Action seems to install Swift 5.7.1 when Swift 5.7 is requested

### ISSUE THREAD

**Issue by redsun82** [swift-actions/setup-swift#503]
**Describe the bug**
After adding support for 5.7.1 it seems that version is set up also when version 5.7 is explicitly requested.

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): swift-actions/setup-swift@v1
 - Platform (`runs-on`): ubuntu-latest, macos-latest
 - Swift version (`swift-version`): 5.7

An example of the issue arising can be seen [here](https://github.com/github/codeql/actions/runs/3572887098/jobs/6006402409) for macOS and [here](https://github.com/github/codeql/actions/runs/3572887098/jobs/6006320622) for Linux.

```
/opt/hostedtoolcache/swift-Ubuntu/5.7.1/x64/usr/bin/swift --version
Swift version 5.7.1 (swift-5.7.1-RELEASE)
```

The failure of those tests is compatible with what we know (we are in the process of making our `codeql` tool compatible with Swift 5.7.1, but that work was not merged yet).

When using v1.19 of the action [the problem goes away](https://github.com/github/codeql/actions/runs/3573116678/jobs/6006819258).

**Comment by fwal** [comment]
Hi @redsun82! 👋🏻 

This is probably due to that the action uses full semantic versioning which slightly differs from version handling that Swift uses (omitting "0" patch versions).
In short "5.1" is treated as "5.1.X" -> "5.1.1". For locking into Swift version "5.1", use "5.1.0" as `swift-version`.

We might revisit this in the future for v2 of this action.

See the [Readme](https://github.com/swift-actions/setup-swift#note-about-versions) for full explanation. 🙂

Hope it helps!
