### ISSUE TITLE
The process '/usr/bin/gpg' failed with exit code 2

### ISSUE THREAD

**Issue by soumyamahunt** [swift-actions/setup-swift#506]
**Describe the bug**
Seems similar to #344. Full logs can be found [here](https://github.com/SwiftyLab/AsyncObjects/actions/runs/3620640829/jobs/6105665991).

**Workflow configuration:**
 - Action version (`uses`): `swift-actions/setup-swift@v1.20`
 - Platform (`runs-on`): `ubuntu-latest`
 - Swift version (`swift-version`): `5.6`

**Comment by recons** [comment]
I had a similar issue. Probably, this is because ubuntu-latest became ubuntu 22 by latest update and there is no such swift package for that version.
Setting `runs-on: ubuntu-20.04` worked for me
<img width="759" alt="image" src="https://user-images.githubusercontent.com/8981788/206422535-ada60e2d-81c8-45a1-9c12-d5fcecef8243.png">
